apiVersion: v1
kind: Service
metadata:
  labels:
    app: cookie-database
  name: cookie-database-service
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: cookie-database
  type: NodePort
