apiVersion: v1
kind: Service
metadata:
  labels:
    app: cookie-frontend
  name: cookie-frontend-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: cookie-frontend
  type: NodePort
