apiVersion: v1
kind: Service
metadata:
  labels:
    app: cookie-backend
  name: cookie-backend-service
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: cookie-backend
  type: NodePort
